# Generated by Django 2.2.16 on 2020-10-26 19:35

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pick',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pick_id', models.CharField(blank=True, max_length=128)),
                ('user_type', models.CharField(default=False, max_length=8)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='date published')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted', models.CharField(default=False, max_length=128)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
            ],
            options={
                'db_table': 'Pick',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='PickItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('active', models.BooleanField(default=True)),
                ('pick', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pick.Pick')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.Product')),
            ],
            options={
                'db_table': 'PickItem',
            },
        ),
    ]
