# Generated by Django 2.2.16 on 2020-10-26 20:03

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pick', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Buy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_price', models.IntegerField()),
                ('expected_delivery_time', models.DateField(auto_now=True)),
                ('delivery_state', models.CharField(default=True, max_length=128)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='date published')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted', models.CharField(default=False, max_length=128)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('product_buy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pick.PickItem')),
            ],
            options={
                'db_table': 'buys',
            },
        ),
    ]
