# Generated by Django 2.2.16 on 2020-10-26 16:22

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64, verbose_name='상품명')),
                ('price', models.IntegerField(verbose_name='가격')),
                ('discount', models.IntegerField(verbose_name='할인')),
                ('description', models.TextField(verbose_name='설명')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='date published')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted', models.CharField(default=False, max_length=128)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
            ],
            options={
                'verbose_name': '상품',
                'db_table': 'products',
            },
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, upload_to='images')),
                ('post', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='product.Product')),
            ],
        ),
    ]
